from datetime import datetime
dt1=datetime(year=2020,month=6,day=28)
dt2=datetime(year=2017,month=5,day=11,hour=5,minute=45)
dt3=datetime(year=2019,month=11,day=22)
print(dt1)
print(dt2)
print(dt3)
print(dt1.year)
print(dt2.month)
print(dt3.month)
print(dt2.year)
print(dt3.day)
#datetime method and datetime class
ct=datetime.now()
print(ct.year)
print(ct.month)
print(ct.day)
ct1=datetime.today()
print(ct1.hour)
print(ct1.min)
print(ct1.second)
