#this program is list data type
list1=[10,20,20,30,10,'Ram',10.5,'ram']
print(list1[0])
print(list1)

print ("*"*20 ,"append function","*"*20)
list1.append("GGPA")
print(list1)
print ("*"*20 ,"copy function","*"*20)
list1.copy()
print(list1)
print ("*"*20 ,"count function","*"*20)
print(list1.count(20))
print ("*"*20 ,"remove function","*"*20)
list1.remove("ram")
print(list1)
print ("*"*20 ,"insert function","*"*20)
list1.insert(2,90)
print(list1)
print ("*"*20 ,"index function","*"*20)
print(list1.index("Ram"))
print ("*"*20 ,"Reverse function","*"*20)
list1.reverse()
print(list1)
print ("*"*20 ,"index function","*"*20)
list1.pop()
print(list1)
print ("*"*20 ,"sort function","*"*20)
print("sort() method is not supported between instance of float and string")
print(list1)

